# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f1e3107a66e0caf554fe82087fd579bdbb9728296237366631936d7d6c2f2465074ef19853e725fdd3245072e35d7992ddcf2b390376944fdb542b330a6206f

test:
  secret_key_base: 94312071da164042efabf28768cb6f41a6776fdc68aa5d369162e72f9b89b3fd4fe4002226c950020d0bd6843bde916a41485a6d3405e0337bd7defceb2bc2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
